version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root      
    ports:
      - "5432:5432"
    volumes:
      - /postgres-data:/var/lib/postgresql/data  
    networks:
      - default_net

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "gw@alura.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "54321:80"
    depends_on:
      - postgres
    networks:
      - default_net
  
  go-app:
    image: gweisheimer/go-app:0.1-alpine
    environment:
      HOST: "postgres"
      DBPORT: "5432"
      USER: "root" 
      PASSWORD: "root" 
      DBNAME: "root"
    ports:
      - "8181:8080"
    #volumes:
    #  - /home/gabriel/git/alura/curso-go-testes:/app
    #command: go run /app/main.go
    depends_on:
      - postgres
    networks:
      - default_net

networks:
  default_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.1/16


